server:
  port: 8881
xxl:
  job:
    admin:
      addresses: http://101.43.190.82:8888/xxl-job-admin
    executor:
      appname: xxl-job-executor-sample
      port: 9999
      address: http://trhrru.natappfree.cc